name: 'Check'
description: 'Run linter, typecheck, and build'

runs:
  using: 'composite'
  steps:
    - name: Run linter
      shell: bash
      run: pnpm run lint

    - name: Run typecheck
      shell: bash
      run: pnpm run typecheck

    - name: Build application
      shell: bash
      run: pnpm run build

