name: 'E2E Tests'
description: 'Run Playwright E2E tests'

inputs:
  base-url:
    description: 'Base URL for Playwright tests'
    required: false
    default: 'http://localhost:3000'
    type: string

runs:
  using: 'composite'
  steps:
    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run E2E tests
      shell: bash
      env:
        PLAYWRIGHT_BASE_URL: ${{ inputs.base-url }}
      run: npm run test

